---
title: "UK Paygap"
author: "Matthew Hondrakis"
date: '2022-06-29'
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, dpi = 500)
library(tidyverse)
library(patchwork)
library(scales)
library(lubridate)
theme_set(theme_bw())
```



```{r}
paygap <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-06-28/paygap.csv')
SIC <- read_csv("C:/Users/Matthew Hondrakis/Downloads/SIC07_CH_condensed_list_en.csv")
```



```{r}
paygap %>% 
  arrange(-abs(diff_mean_hourly_percent)) %>% 
  select(employer_name, diff_mean_hourly_percent, employer_size)

paygap %>% 
  arrange(-abs(diff_median_hourly_percent)) %>% 
  select(employer_name, diff_median_hourly_percent, employer_size)
```



```{r}
paygap %>% 
  ggplot(aes(employer_size, diff_mean_hourly_percent)) +
  geom_boxplot()

paygap %>% 
  filter(employer_size != "Not Provided") %>% 
  mutate(new = as.factor(parse_number(employer_size))) %>% 
  ggplot(aes(new, diff_mean_hourly_percent)) + geom_boxplot()
```


```{r}
test_data <- paygap %>% 
  filter(employer_size != "Not Provided") %>% 
  mutate(new = as.factor(parse_number(employer_size)))

summary(aov(diff_mean_hourly_percent ~ new, test_data))

pairwise.t.test(paygap$diff_mean_hourly_percent, paygap$employer_size)
```



```{r}
paygap %>% 
  mutate(color = ifelse(diff_median_hourly_percent > 0, "Men", "Women"),
         diff = abs(diff_median_hourly_percent)) %>% 
  group_by(employer_name) %>% 
  arrange(-abs(diff_median_hourly_percent)) %>% 
  head(20) %>% 
  ggplot(aes(diff, 
             fct_reorder(str_to_title(employer_name), diff),
             fill = color)) + 
  geom_col() +
  labs(y = "", x = "")

gplot <- function(x){
  paygap %>% 
    mutate(color = ifelse({{x}} > 0, "Men", "Women"),
           diff = abs({{x}})) %>% 
    group_by(employer_name, color) %>% 
    summarize(diff = max(diff)) %>% 
    arrange(-abs(diff)) %>% 
    head(20) %>% 
    ggplot(aes(diff, 
               fct_reorder(str_to_title(employer_name), diff),
               fill = color)) + 
    geom_col() +
    labs(y = "", x = "")
}
gplot(diff_median_hourly_percent)

gplot(diff_mean_hourly_percent)
```



```{r}
paygap_joined <- paygap %>% 
  separate_rows(sic_codes, sep = ":") %>% 
  left_join(SIC, by = c("sic_codes" = "SIC Code"))
paygap_joined %>% 
  group_by(Description) %>% 
  summarize(m = mean(diff_median_hourly_percent)) %>% 
  arrange(-abs(m)) %>% 
  mutate(col = ifelse(m > 0, "Men", "Women"),
         m = abs(m)) %>% 
  head(20) %>% 
  ggplot(aes(m, fct_reorder(Description, m), fill = col)) + geom_col(color = "black") +
  scale_x_continuous(labels = scales::label_percent(scale = 1)) + 
  scale_fill_brewer(palette = "Set2", direction = -1) +
  labs(y = "Industry", x = "Average Percent Difference", title = "Average Median Gender Paygap Difference",
       subtitle = "Average of median hourly paygap") +
  theme(plot.title = element_text(hjust = 0.5)) 


paygap_joined %>% 
  group_by(Description) %>% 
  summarize(m = mean(diff_mean_hourly_percent)) %>% 
  arrange(-abs(m)) %>% 
  mutate(col = ifelse(m > 0, "Men", "Women"),
         m = abs(m)) %>% 
  head(20) %>% 
  ggplot(aes(m, fct_reorder(Description, m), fill = col)) + geom_col(color = "black") +
  scale_x_continuous(labels = scales::label_percent(scale = 1)) + 
  scale_fill_brewer(palette = "Set2", direction = -1) +
  labs(y = "Industry", x = "Average Percent Difference", title = "Average Gender Paygap Difference") +
  theme(plot.title = element_text(hjust = 0.5)) 
```

