---
title: "Women's Rugby"
author: "Matthew Hondrakis"
date: '2022-05-24'
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, dpi = 500)
library(tidyverse)
library(patchwork)
theme_set(theme_bw())
```


```{r}
sevens <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-05-24/sevens.csv')
fifteens <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-05-24/fifteens.csv')

```


```{r}
which(is.na(sevens$row_id))

sevens$row_id[1] <- 1
sevens$row_id[3990] <- 3990

sevens %>% 
  pivot_longer(starts_with("team")) %>% 
  select(row_id, name, value, winner, loser)
```



```{r}
gplot <- function(data, x, y = 10){
  data %>% 
    count({{x}}, sort = TRUE) %>% 
    head({{y}}) %>% 
    ggplot(aes(n, fct_reorder({{x}}, n))) + geom_col()
}

gplot(sevens, winner) + labs(y = "", title = "Sevens") +
gplot(fifteens, winner) + labs(y = "", title = "Fifteens") + 
  plot_annotation(title = "Top 10 Counts of Wins", 
                  theme = theme(plot.title = element_text(hjust = 0.5))) 
```


```{r}
sevens %>% 
  count(stage, sort = TRUE)

gplot(sevens %>% filter(stage == "Final"), winner) + 
  labs(title = "Number of Finals Won", y = "") +
  theme(plot.title = element_text(hjust = 0.5))
```



```{r}
sevens %>% 
  filter(stage == "Final") %>% 
  count(winner, sort = TRUE) %>% 
  head(10)



sevens %>% 
  select(stage, winner, date) %>% 
  filter(stage == "Final") %>% 
  filter(winner %in% (sevens %>% 
           filter(stage == "Final") %>% 
           count(winner, sort = TRUE) %>% 
           head(10) %>% 
           pull(winner))) %>% 
  arrange(date) %>% 
  group_by(winner) %>% 
  mutate(c = 1, counter = cumsum(c)) %>%
  bind_rows(
    sevens %>% 
      select(stage, winner, date) %>% 
      filter(stage == "Final",
             winner %in% (sevens %>% 
           filter(stage == "Final") %>% 
           count(winner, sort = TRUE) %>% 
           head(10) %>% 
           pull(winner))) %>% 
      mutate(date = max(date), 
             c = 1, 
             counter = case_when(winner == "New Zealand" ~ 38,
                                 winner == "Japan" ~ 22,
                                 winner == "Australia" ~ 21,
                                 winner == "Brazil" ~ 21,
                                 winner == "Canada" ~ 15,
                                 winner == "England" ~ 15,
                                 winner == "China" ~ 12,
                                 winner == "Russia" ~ 10,
                                 winner == "South Africa" ~ 10,
                                 winner == "France" ~ 9))
  ) %>%
  ggplot(aes(date, counter, 
             color = fct_reorder(winner, counter, max, .desc = TRUE))) +
  geom_line() + labs(y = "Cumulative Wins", 
                     title = "Cumulative Wins in the Finals over time",
                     color = "")
```


