---
title: "Pell Grant"
author: "Matthew"
date: "2022-08-30"
output: 
  github_document:
    toc: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, dpi = 500)
library(tidyverse)
library(patchwork)
library(scales)
library(usmap)
library(ggthemes)
library(ggfortify)
theme_set(theme_bw())
```


```{r, include = FALSE}
pell <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-08-30/pell.csv')
```

# Clean Data
```{r}
names(pell) <- names(pell) %>% tolower()

tbjoin <- as_tibble(cbind(state_name = state.name, state = state.abb))

pell <- pell %>% 
  left_join(tbjoin)

pell %>% filter(is.na(state_name)) %>% count(state, sort = TRUE)

pell <- pell %>% 
  mutate(state_name = case_when(state == "PR" ~ "Puerto Rico",
                                state == "DC" ~ "District of Columbia",
                                state == "GU" ~ "Guam",
                                state == "VI" ~ "Virgin Islands",
                                state == "AS" ~ "American Samoa",
                                state == "FM" ~ "Federated States of Micronesia",
                                state == "MH" ~ "Marshall Islands",
                                state == "MP" ~ "Northern Mariana Islands",
                                state == "PW" ~ "Palau",
                                TRUE ~ as.character(state_name)))
```



# EDA
```{r}
pell %>% 
  ggplot(aes(award)) + geom_histogram() +
  scale_x_log10()

pell %>% 
  group_by(state_name) %>% 
  mutate(median = median(award, na.rm = TRUE)) %>% 
  filter(median >= 1920043) %>% 
  ggplot(aes(award, fct_reorder(state_name, median))) + geom_boxplot() +
  scale_x_log10(label = dollar) + labs(y = "State", x = "Pell Grant Award")

pell %>% 
  group_by(year) %>% 
  summarize(award = median(award, na.rm = TRUE)) %>% 
  ggplot(aes(year, award)) + geom_line()
```



## Map
```{r}
plot_usmap(data = pell %>% 
             filter(year == max(year)) %>% 
             group_by(state) %>% 
             summarize(award = median(award, na.rm = TRUE)), 
           values = "award") +
  theme(legend.position = "right")
  
```

## Top Pell Grant Recipients
```{r}
pell %>% 
  group_by(name, state_name) %>% 
  summarize(award = max(award)) %>% 
  head(10) %>% 
  mutate(name = str_remove_all(name, "\""),
         name = ifelse(grepl("Art Institute", name), 
                       "Art Institute of Pittsburgh", name)) %>% 
  ggplot(aes(award, fct_reorder(name, award))) + 
  geom_col(color = "black", aes(fill = state_name)) +
  scale_x_log10(labels = dollar, breaks = c(1e3, 1e5, 1e7)) + 
  ggthemes::theme_fivethirtyeight() +
  labs(fill = "")
```

## Pell Grants per Recipients
```{r}
pell %>% 
  mutate(per = award/recipient) %>% 
  arrange(-per) %>% 
  head(10) %>% 
  ggplot(aes(per, fct_reorder(name, per))) + 
  geom_col(color = "black", aes(fill = state)) + 
  scale_x_log10() + theme_fivethirtyeight() +
  labs(fill = "", x = "Average award per recipient", 
       y = "School", title = "Top 10 Schools with Highest Pell Grants per Recipient")
```


## Award by recipient
```{r}
pell %>% 
  group_by(recipient, state) %>% 
  summarize(m = median(award)) %>% 
  ggplot(aes(recipient, m)) + geom_line(aes(color = state)) +
  theme(legend.position = "none") + geom_smooth(method = "lm", se = FALSE) +
  scale_x_continuous(trans=scales::pseudo_log_trans(base = 10)) +
  scale_y_continuous(trans=scales::pseudo_log_trans(base = 10))
```

# Model
```{r}
model <- lm(log(award + 1) ~ log(recipient + 1), pell) 

model %>% summary()
```


```{r}
autoplot(model, which = 1:6, ncol = 3, label.size = 2)
```


```{r}
model %>% broom::augment() %>% 
  arrange(desc(abs(.std.resid))) %>%
  group_by(`log(award + 1)`) %>% 
  summarize(sum = sum(.std.resid)) %>% 
  ggplot(aes(`log(award + 1)`, sum)) + geom_point(aes(size = abs(sum)))
```

The overwhelming majority of the error comes from instances where the award is 0.

```{r}
pell %>% filter(award == 0)
```



## Model Prediction
```{r}
pell %>% 
  filter(award > 0) %>% 
  mutate(overbelow = 
           ifelse(log(award) > predict(model, pell %>% filter(award > 0)), 1, 0)) %>% 
  group_by(state) %>% 
  summarize(avg = mean(overbelow == 1)) %>% 
  arrange(-avg)

pell %>% 
  filter(award > 0) %>% 
  mutate(overbelow = 
           ifelse(log(award) > predict(model, pell %>% filter(award > 0)), 1, 0)) %>% 
  group_by(state) %>% 
  summarize(avg = mean(overbelow == 1)) %>% 
  ungroup() %>% 
  summarize(m = mean(avg > 0.5))
```

71% of states received more than the model predicted using the number of recipients as a predictor. 



## Map
```{r}
pell %>% 
  filter(award > 0) %>% 
  mutate(overbelow = 
           ifelse(log(award) > predict(model, pell %>% filter(award > 0)), 1, 0)) %>% 
  group_by(state) %>% 
  summarize(avg = mean(overbelow == 1)) %>% 
  plot_usmap(data = ., values = "avg") +
  scale_fill_gradient2(low = "red", mid = "white", high = "blue", midpoint = 0.5)
```



```{r}
pell %>% 
  filter(award == 0) %>% 
  select(state_name, recipient, name) %>% 
  mutate(predicted = exp(predict(model, .))) %>% 
  arrange(-recipient)
```

