---
title: "Art Publications"
author: "Matthew"
date: "2023-01-17"
output: 
  github_document:
    toc: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, dpi = 500)
library(tidyverse)
library(scales)
library(patchwork)
library(sysfonts)
library(showtext)
font_add_google("Roboto Condensed", "Roboto Condensed")
showtext_auto()
theme_set(theme_bw())
theme_update(plot.title = element_text(hjust = 0.5),
             text = element_text(family = "Roboto Condensed"))
```

```{r}
artist <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-01-17/artists.csv')

# shorten column names by removing 'artist_' from it
artist <- artist %>% 
  rename_with(~gsub("artist_", "", .x))
```

# Data Cleaning

## Missing Values

```{r}
skimr::skim(artist) %>% select(skim_type, skim_variable, n_missing)
```

## Counts

```{r}
artist %>% 
  count(race, sort = TRUE)
```

*race* has a string called N/A, this should be replaced with NA values as missing data.

```{r}
artist <- artist %>% 
  mutate(race = ifelse(race == "N/A", NA, race))
```

# Exploratory Data Analysis

## Race

```{r}
artist %>% 
  group_by(ethnicity) %>% 
  count(race, sort = TRUE) %>% 
  drop_na() %>% 
  ggplot(aes(n, fct_reorder(race, n, sum))) +
  geom_col(color = "black", aes(fill = fct_rev(ethnicity))) +
  scale_x_log10() +
  labs(y = "", x = "", fill = "")
```

### Years

```{r}
artist %>% 
  drop_na() %>% 
  group_by(year) %>% 
  count(race) %>% 
  ggplot(aes(year, n, color = race)) +
  geom_line() +
  labs(title = "Art Publications", x = "Year", y = "", color = "")

artist %>% 
  drop_na() %>% 
  ggplot(aes(year, fill = race, color = race)) +
  geom_density(alpha = 0.5) +
  labs(title = "Proportion of Publications of each Race",
       x = "Year", y = "")
```

```{r}
artist %>% 
  filter(race_nwi == "Non-White") %>% 
  group_by(year) %>% 
  count(book) %>% 
  ggplot(aes(year, n, color = book)) +
  geom_line()

artist %>% 
  ggplot(aes(fill = book, x = race_nwi)) +
  geom_bar(position = "fill") +
  scale_y_continuous(label = percent_format())
```

### Book

```{r}
artist %>% 
  count(race_nwi, book) %>% 
  group_by(race_nwi) %>% 
  mutate(pct = n/sum(n)) %>% 
  ggplot(aes(x = race_nwi, y = pct, fill = fct_rev(book), label = percent(pct))) + 
  geom_col(position = 'fill') + 
  geom_text(position = "fill", size = 4, vjust = 2) + 
  scale_y_continuous(labels = percent) +
  scale_fill_manual(values = c("steelblue2", "green3")) +
  labs(y = "", x = "", fill = "", title = "Where Non-Whites Publish Art") 
```

We can see that the majority of Non-White artists had their art published on **Gardener**.

### Amount of Space on the Page

```{r}
artist %>% 
  drop_na() %>% 
  group_by(race) %>% 
  summarize(n = n()) %>% 
  arrange(-n) %>% 
  knitr::kable()

artist %>% 
  drop_na() %>% 
  ggplot(aes(space_ratio_per_page_total, fill = race)) +
  geom_histogram() +
  facet_wrap(~race, scales = "free", ncol = 2) +
  theme(legend.position = "none")
```

```{r}
artist %>%
  drop_na() %>% 
  group_by(race) %>% 
  summarize(median = median(space_ratio_per_page_total)) %>% 
  ggplot(aes(median, fct_reorder(race, median))) +
  geom_col(color = "black", fill = "steelblue2") +
  geom_text(aes(label = round(median, 2)), hjust = 1.5) +
  labs(y = "", x = "Median", title = "Amount of Space Art takes on a Page by Race")
```

## Artist

```{r}
artist %>% 
  group_by(name, nationality) %>% 
  summarize(avg_space = mean(space_ratio_per_page_total, na.rm = TRUE)) %>% 
  ungroup() %>% 
  slice_max(avg_space, n = 10) %>% 
  ggplot(aes(avg_space, fct_reorder(name, avg_space), fill = nationality)) +
  geom_col(color = "black") +
  labs(y = "", x = "", title = "Average Art Space on Page by Artist", 
       fill = "Nationality")
```
