---
title: "Technology Adoption"
author: "Matthew"
date: '2022-07-19'
output: 
  github_document:
    toc: true
editor_options: 
chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, dpi = 500)
library(tidyverse)
library(patchwork)
library(scales)
library(lubridate)
library(countrycode)
library(gghighlight)
theme_set(theme_bw())
```


```{r}
technology <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-07-19/technology.csv')

technology <- technology %>% 
  bind_cols(country = countrycode(technology$iso3c, origin = 'iso3c', destination = 'country.name'),
            continent = countrycode(technology$iso3c, origin = 'iso3c', destination = 'continent'))
```


```{r}
skimr::skim(technology)
```


# EDA
```{r}
technology %>% 
  count(label, sort = TRUE) 

technology %>% 
  count(category, sort = TRUE)

technology %>% 
  group_by(group) %>% 
  count(category)
```



```{r}
technology %>%  
  drop_na() %>% 
  group_by(year, continent) %>% 
  summarize(value = mean(value) + 1) %>% 
  ggplot(aes(year, value, color = fct_reorder(continent, value, max, .desc = TRUE))) + geom_line() +
  scale_y_log10() + scale_x_continuous(breaks = seq(1820, 2020, 20)) + 
  labs(title = "Overall Technology use over time", color = "")
```




# Vaccines
```{r}
names <- technology %>% 
  filter(category == "Vaccines") %>% 
  count(variable, sort = TRUE) %>% 
  head(5) %>% 
  pull(variable)

technology %>% 
  count(iso3c, sort = TRUE)


technology %>%
  group_by(year) %>% 
  summarize(value = mean(value)) %>% 
  ggplot(aes(year, value)) +
  geom_line() + theme(legend.position = "none")


technology %>%
  filter(variable %in% names) %>% 
  group_by(year) %>% 
  summarize(value = mean(value)) %>% 
  ggplot(aes(year, value)) +
  geom_line() + theme(legend.position = "none")
```



```{r}
technology %>%  
  drop_na() %>% 
  filter(category == "Vaccines") %>% 
  group_by(year, continent) %>% 
  summarize(value = mean(value) + 1) %>% 
  ggplot(aes(year, value, color = fct_reorder(continent, value, max, .desc = TRUE))) + geom_line() +
  scale_y_log10() + scale_x_continuous(breaks = seq(1820, 2020, 20)) + 
  labs(title = "Average Vaccination Rate per Continent over time", color = "")
```



```{r}
technology %>% 
  filter(value == 0) %>% 
  group_by(group) %>% 
  summarize(n = n())
```


# Transport
```{r}
technology %>% 
  filter(category == "Transport") %>% 
  count(group, sort = TRUE)

technology %>% 
  filter(category == "Transport") %>% 
  count(label, sort = TRUE)
```


## Vehicles
```{r}
gplot <- function(data, x){
  data %>% 
    group_by(continent, year) %>% 
    summarize(value = {{x}}) %>% 
    ggplot(aes(year, value, color = fct_reorder(continent, value, max))) + geom_line() +
    labs(color = "")
}


(technology %>% 
  filter(grepl("vehicle", label)) %>% 
  group_by(continent, year) %>% 
  gplot(mean(value)) + scale_y_log10()) /
(technology %>% 
  filter(grepl("vehicle", label)) %>% 
  gplot(median(value)) + scale_y_log10())
```


## Routes
```{r}
technology %>% 
  filter(grepl("Geographical", label)) %>% 
  gplot(mean(value))
```



# Hospital
```{r}
technology %>% 
  filter(group == "Consumption" & grepl('Hospital', category)) %>% 
  count(label, sort = TRUE) 


technology %>% 
  filter(grepl('hospital', label)) %>% 
  group_by(label) %>% 
  summarize(n = mean(value)) %>% 
  arrange(-n)
```


## Transplants
```{r}
technology %>% 
  filter(grepl('Hospital', category)) %>% 
  filter(grepl('transplants', label)) %>% 
  mutate(label = str_replace(label, 'transplants', "")) %>% 
  group_by(label, year, continent) %>% 
  summarize(value = mean(value)) %>% 
  ggplot(aes(year, value, color = label)) + geom_line() +
  facet_wrap(~continent) +
  labs(color = "", title = "Type of Transplants over time")
```


```{r}
technology %>% 
  filter(grepl("dialysis", label)) %>% 
  gplot(mean(value))

technology %>% 
  filter(grepl("dialysis", label)) %>% 
  mutate(label = ifelse(grepl("home", label), "home", "hospital")) %>% 
  group_by(label, year) %>% 
  summarize(value = mean(value)) %>% 
  ggplot(aes(year, value, color = label)) + geom_line() +
  labs(color = "", title = "Dialysis at Home or Hopsital", 
       caption = "Data goes from 1968 to 2002") + 
  theme(plot.caption = element_text(hjust = 0.5)) +
  scale_x_continuous(breaks = c(1968, seq(1974, 2002, 4)))
```


## Tomography
```{r}
technology %>% 
  filter(grepl("Tomography", label) & grepl("total", label)) %>% 
  group_by(label, year) %>% 
  summarize(value = mean(value)) %>% 
  ggplot(aes(year, value, color = label)) + geom_line() +
  scale_y_log10(label = comma)

technology %>% 
  filter(grepl("Tomography", label) & grepl("total", label)) %>% 
  gplot(mean(value))
```



# Country
## Dialysis
```{r}
technology %>% 
  filter(grepl("dialysis", label)) %>% 
  mutate(temp_country = ifelse(grepl("United States", country), country, "All Other")) %>%
  group_by(year, temp_country) %>% 
  summarize(value = mean(value)) %>% 
  ggplot(aes(year, value, color = temp_country)) + geom_line()
```


```{r}
technology %>% 
  filter(grepl("Geographical", label)) %>%  
  mutate(continent = ifelse(grepl("United States", country), country, "All Other")) %>%
  gplot(sum(value))
```


# Nested Country Model

## Dialysis
```{r}
tidy_tech <- technology %>% 
  filter(grepl("dialysis", label)) %>% 
  group_by(country, year) %>% 
  summarize(value = mean(value)) %>% 
  nest(-country) %>% 
  mutate(model = map(data, ~lm(value ~ year, .)),
         tidy = map(model, broom::tidy)) %>% 
  unnest(tidy)

tidy_tech %>% 
  filter(term == "year" & p.value < 0.05) %>% 
  arrange(-abs(estimate))

tidy_tech %>% 
  filter(term == "year" & p.value > 0.05) %>% 
  arrange(-abs(estimate)) 
```



```{r}
tidy_tech_joined <- tidy_tech %>% 
  filter(term == "year") %>% 
  inner_join(technology %>% distinct(country, continent)) 

tidy_tech_joined %>% 
  filter(country != "Iceland") %>% 
  ggplot(aes(estimate, fct_reorder(country, estimate))) +
  geom_col(aes(fill = continent)) + 
  geom_errorbarh(aes(xmin = estimate - std.error, xmax = estimate + std.error)) +
  labs(y = "") + scale_x_log10(limits = c(1, 10000), labels = comma)
```


```{r}
tidy_names <- tidy_tech_joined %>% 
  arrange(desc(estimate)) %>% 
  head(10) %>% 
  pull(country)

technology %>% 
  filter(grepl("dialysis", label) & country %in% tidy_names) %>% 
  group_by(country, year) %>% 
  summarize(value = mean(value)) %>% 
  ggplot(aes(year, value)) + geom_line() + geom_smooth(method = "lm", se = FALSE) +
  facet_wrap(~country, scales = "free")
```


# Internet
```{r}
technology %>% 
  filter(grepl("internet", label)) %>% 
  count(label, sort = TRUE)

internet <- technology %>% 
  filter(grepl("internet", label))
```


```{r}
internet %>% 
  gplot(mean(value))

(internet %>% 
  filter(grepl("People", label)) %>% 
  ggplot(aes(year, value, color = country)) +
  geom_line() + theme(legend.position = "none") +
  gghighlight(max(value), max_highlight = 5L) +
  labs(title = "People with internet access", subtitle = "Not per capita")) +
(internet %>% 
  filter(!grepl("People", label)) %>% 
  ggplot(aes(year, value, color = country)) +
  geom_line() + theme(legend.position = "none") +
  gghighlight(max(value), max_highlight = 5L) +
  labs(title = "Secure Internet Servers") + scale_x_continuous(breaks = seq(2010, 2020, 2)))
```



```{r}
technology %>% 
  filter(country == "United States") %>% 
  ggplot(aes(year, value, color = label)) +
  geom_line() + gghighlight(max(value), max_highlight = 5L) +
  scale_y_log10()
```

