---
title: "Baby Names"
author: "Matthew"
date: "3/21/2022"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
library(tidyverse)
library(broom)
theme_set(theme_bw())
```


```{r}
babynames <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-03-22/babynames.csv')

babynames <- babynames %>%
  mutate(sex = factor(sex))
```


# EDA
```{r}
babynames %>%
  group_by(name) %>%
  summarize(k = sum(n)) %>%
  arrange(-k) %>%
  head(20) %>%
  knitr::kable()
```


```{r}
babynames %>%
  group_by(name) %>%
  summarize(min = min(n),
            max = max(n),
            diff = max - min) %>%
  arrange(-diff)
```


```{r}
babynames %>%
  filter(name == "James") %>%
  ggplot(aes(year, n)) + geom_point() + geom_smooth(method = "lm") +
  facet_wrap(~ sex)

babynames %>%
  filter(name == "James") %>%
  arrange(year) %>%
  select(year, n)
```


# Model
```{r}
library(tidymodels)
set.seed(123)
```


```{r}
split_data <- initial_split(babynames %>% filter(name %in% sample(babynames$name, 100)), strata = name)

train_data <- training(split_data)
test_data <- testing(split_data)
```


## Build Model
```{r}
mod <- logistic_reg()

rec <- recipe(sex ~ name + n, train_data) %>%
  step_dummy(all_nominal_predictors())
  
mod_wf <- workflow() %>%
  add_model(mod) %>%
  add_recipe(rec)
```


## Fit Model and Evaluate
```{r}
fit <- fit(mod_wf, train_data)

augment(fit, test_data) %>%
  roc_auc(sex, .pred_F)
```


## Fit Model 2
```{r}
mod2_aug <- mod %>%
  fit(sex ~ name:n, train_data) %>%
  augment(test_data)

mod2_aug %>%
  roc_auc(sex, .pred_F)
```



```{r}
mod3_aug <- mod %>%
  fit(sex ~ name, train_data) %>%
  augment(test_data)

mod3_aug %>%
  roc_auc(sex, .pred_F)
```


## All models plot
```{r, dpi = 500}
fit %>%
  augment(test_data) %>%
  mutate(model = "1") %>%
  bind_rows(mod2_aug %>%
              mutate(model = "2")) %>%
  bind_rows(mod3_aug %>%
              mutate(model = "3")) %>%
  group_by(model) %>%
  roc_curve(sex, .pred_F) %>%
  autoplot() +
  labs(title = "Both Models") +
  theme(plot.title = element_text(hjust = 0.5))
```


### Checking wrongly predicted names of Model 2
```{r}
(names <- mod2_aug %>%
  filter(sex != .pred_class) %>%
  count(name, sort = TRUE))

train_data %>%
  filter(name %in% names$name) %>%
  ggplot(aes(y = name, fill = sex)) + geom_bar(position = "dodge")

test_data %>%
  filter(name %in% names$name) %>%
  ggplot(aes(y = name, fill = sex)) + geom_bar(position = "dodge")
```



```{r, dpi = 500}
train_data %>%
  filter(name %in% names$name[1:6]) %>%
  ggplot(aes(year, n, color = sex)) + geom_line() +
  facet_wrap(~name, scales = "free") +
  labs(title = "Top 6 Names incorrectly classified")
```

