---
title: "Bee Colony"
author: "Matthew"
date: "1/11/2022"
output: 
  html_document:
    keep_md: true
    toc: true
    toc_float: true
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
theme_set(theme_bw())

colony <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-01-11/colony.csv')
stressor <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-01-11/stressor.csv')

colony$year <- as.numeric(colony$year)

beecolony <- colony %>%
  inner_join(stressor, by = c("year", "months", "state")) %>%
  pivot_wider(names_from = "stressor", values_from = "stress_pct")

beecolony <- na.omit(beecolony)
```


# Explore

```{r}
beecolony %>%
  select(where(is.numeric), -year) %>%
  gather() %>%
  ggplot(aes(value)) + geom_histogram() + scale_x_log10(labels = scales::comma) + facet_wrap(~key, scales = "free", ncol = 3)

beecolony %>%
  arrange(-colony_added) %>%
  select(colony_added)
```

## Colony_* Function and plots
```{r}
gplot <- function(x){
  colony %>%
    filter(!is.na({{x}})) %>%
    mutate(across(where(is.character), as.factor)) %>%
    distinct(months, year, state, {{x}}) %>%
    ggplot(aes({{x}}, reorder(state, {{x}}, order = TRUE))) + geom_col() + labs(y = "")
}

gplot(colony_n)
```


## Stressors
```{r}
levels <- c("Disesases", "Unknown", "Other", "Pesticides", "Other pests/parasites", "Varroa mites")

stressor %>%
  drop_na() %>%
  mutate(stressor = as.factor(stressor), stressor = fct_relevel(stressor, levels = levels)) %>%
  group_by(year, stressor) %>%
  summarize(n = mean(stress_pct)) %>%
  ggplot(aes(year, n, fill = stressor)) + geom_col(position = "dodge") + 
  scale_y_continuous(labels = scales::percent_format(scale = 1))

```


```{r}
beecolony %>%
  mutate(months = as.factor(months), 
         months = fct_relevel(months, c("January-March", "April-June", 
                                        "July-September", "October-December"))) %>%
  group_by(months) %>%
  summarize(n = mean(`Varroa mites`)) %>%
  ggplot(aes(months, n, fill = months)) + geom_col() + scale_y_continuous(labels = scales::percent_format(scale = 1)) +
  labs(y = "", x = "", title = "Colonies Destroyed by Varroa mites", subtitle = "On average every year" ) +
  theme(legend.position = "none")

```


```{r}
library(GGally)
colony %>%
  select(contains("colony"), -contains("pct")) %>%
  ggpairs()
```



```{r}
colony %>%
  drop_na() %>%
  ggplot(aes(colony_added, colony_lost)) + geom_point() + scale_x_log10(labels = scales::label_comma()) +
  scale_y_log10(labels = scales::label_comma()) + geom_smooth(method = "lm") + facet_wrap(~months) +
  labs(x = "Colonies added", y = "Colonies lost", title = "Colonies: Lost vs Added", subtitle = "Axes on a log10 scale")

```





