---
title: "Chocolate Bar Ratings"
author: "Matthew"
date: "1/18/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
theme_set(theme_bw())
chocolate <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-01-18/chocolate.csv')
chocolate <- chocolate %>%
  rename(year = review_date) %>%
  separate(ingredients, c("ingredients_amount", "ingredients_type"), extra = "merge") %>%
  mutate(cocoa_percent = as.numeric(str_replace(cocoa_percent, "%", "")),
         ingredients_amount = as.numeric(ingredients_amount))
```

# EDA

## Plot of Numerics
```{r}
chocolate %>%
  keep(is.numeric) %>%
  gather() %>%
  ggplot(aes(value)) + geom_histogram() + facet_wrap(~key, scales = "free")
chocolate %>%
  gather() %>%
  count(value, sort = TRUE)
```

## Plot function
```{r}
ratingplot <- function(x) {
  chocolate %>%
    group_by({{x}}) %>%
    summarize(n = mean(rating)) %>%
    arrange(-n) %>%
    head(10) %>%
    ggplot(aes(n, fct_reorder({{x}}, n))) + geom_col() + labs(x = "Average Rating")
}
ratingplot(company_manufacturer) + labs(y = "Manufacturer")
ratingplot(company_location) + labs(y = "Location")
ratingplot(country_of_bean_origin) + labs(y = "Bean Origin")
```


## Rating by Year
```{r}
chocolate %>%
  group_by(year) %>%
  summarize(n = mean(rating)) %>%
  ggplot(aes(year, n)) + geom_point() + geom_smooth() + ylim(ymin = 0, ymax = 5)
```


## Rating by Cocoa Percent
```{r}
chocolate %>%
  group_by(cocoa_percent) %>%
  summarize(n = mean(rating)) %>%
  ggplot(aes(cocoa_percent, n)) + geom_point() + geom_line() + 
  geom_smooth(se = FALSE) + labs(y = "Mean Rating", x = "Cocoa Percent")
```


## Rating by amount of ingredients
```{r}
chocolate %>%
  drop_na() %>%
  group_by(ingredients_amount) %>%
  mutate(new = mean(rating)) %>%
  ggplot(aes(ingredients_amount, rating, group = ingredients_amount)) + geom_boxplot() + 
  geom_line(aes(x = ingredients_amount, y = new, group = 1), color = "blue") +
  geom_point(aes(x = ingredients_amount, y = new), color = "blue", size = 2) +
  labs(caption = "Blue line/dots represent the average per group")

chocolate %>%
  drop_na() %>%
  group_by(ingredients_amount) %>%
  summarize(Average = mean(rating)) %>%
  ggplot(aes(ingredients_amount, Average)) + geom_line() + labs(title = "Zoomed in")

```



### Ingredients Type
```{r}
chocolate %>%
  drop_na() %>%
  group_by(ingredients_type) %>%
  summarize(Average = mean(rating)) %>%
  ggplot(aes(Average, fct_reorder(ingredients_type, Average), fill = Average)) + geom_col() +
  scale_fill_viridis_c(option = "H", direction = -1) +
  labs(title = "Average Rating of all Ingredients", 
       y = "Ingredients", x = "Average Rating")

chocolate %>%
  drop_na() %>%
  mutate(ingredients_type = fct_lump(ingredients_type, n = 5)) %>%
  group_by(ingredients_type) %>%
  summarize(Average = mean(rating)) %>%
  ggplot(aes(Average, fct_reorder(ingredients_type, Average))) + geom_col() + 
  labs(title = "Average Rating of Top 5 Ingredients", subtitle = "Ratings not in top 5 are collapsed as Other", 
       y = "Ingredients", x = "Average Rating")

```


## Type of Sugar
```{r}
chocolate %>%
  drop_na() %>%
  mutate(sugar = str_detect(ingredients_type, "\\*"),
         sugar = case_when(sugar == FALSE ~ "Real Sugar",
                           sugar == TRUE ~ "Sweetener")) %>%
  ggplot(aes(sugar, rating)) + geom_boxplot() + 
  labs(y = "Rating", x = "Sugar", title = "Ratings separated by synthetic or real sugar",
       subtitle = "There is far more real sugar in the dataset, than sweetener substitutes", 
       caption = "Real Sugar: 2,367     Sweetener: 76")
  
```





