---
title: "Erasmus"
author: "Matthew"
date: "3/8/2022"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
library(tidyverse)
library(anytime)
library(skimr)
library(scales)
library(broom)
theme_set(theme_bw())
```


```{r}
erasmus <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-03-08/erasmus.csv')
erasmus <- erasmus %>%
  rename_with(~ gsub("mobility_","", .x)) %>%
  mutate(start_month = as.Date(anytime(start_month)),
         end_month = as.Date(anytime(end_month)))
```

# EDA
```{r}
skim(erasmus)
```


```{r}
erasmus %>%
  count(participant_age, sort = TRUE) %>%
  head(15) %>%
  ggplot(aes(x = n, y = as.character(participant_age))) + geom_col() + ylab("")
```


```{r}
erasmus %>%
  group_by(participant_gender) %>%
  summarize(m = mean(special_needs == "No"))
```


```{r}
propfun <- function(x){
  erasmus %>%
    count({{x}}, sort = TRUE) %>%
    mutate(prop = n/sum(n))
}

propfun(receiving_organisation_erasmus_code)
propfun(activity_mob)
propfun(duration)
propfun(receiving_city)
propfun(participant_profile)
```


```{r}
erasmus %>%
  group_by(participant_gender) %>%
  count(receiving_city, sort = TRUE)
```


```{r}
erasmus %>%
  filter(100 < abs(participant_age)) %>%
  count(participant_age)
```


```{r}
erasmus %>%
  group_by(participant_gender) %>%
  count(activity_mob) %>%
  ggplot(aes(n, activity_mob, fill = participant_gender)) + 
  geom_col(position = "dodge")
```


```{r}
erasmus %>%
  select(start_month, end_month, duration) %>%
  count(duration) %>% arrange(duration) %>%
  head(20) %>%
  ggplot(aes(n, fct_reorder(as.factor(duration), duration))) + 
  geom_col() + scale_x_log10(labels=comma) +
  labs(y = "Duration", x = "Count")

df <- erasmus %>%
  count(duration)

df %>%
  ggplot(aes(duration, n)) + geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  scale_y_log10() + scale_x_log10()

mod <- lm(log(n) ~ log(duration), df)

mod %>% summary()

df %>%
  mutate(log_pred = predict(mod, df),
         resid = log(n) - log_pred) %>%
  ggplot(aes(log_pred, resid)) + geom_point() +
  geom_hline(yintercept = 0)

```

Bias in residuals: Not a very good linear regression model. 

```{r}

```




