---
title: "Freedom"
author: "Matthew"
date: "2/21/2022"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(broom)
theme_set(theme_bw())
```


```{r}
freedom <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-02-22/freedom.csv")
freedom <- freedom %>%
  rename_with(tolower) %>%
  mutate(is_ldc = fct_rev(as.factor(is_ldc)))
```


# EDA
```{r}
freedom %>%
  select(where(is.numeric)) %>%
  gather() %>%
  ggplot(aes(value)) + geom_histogram() + facet_wrap(~key, scales = "free")
```


## Cl ~ Pr relationship
```{r}
freedom %>%
  lm(cl ~ pr,.) %>%
  summary()
```


## Top countries
```{r}
x <- freedom %>%
  filter(year == 2020) %>%
  mutate(pr = -pr + 8,
         cl = -cl + 8,
         total = cl + pr) %>%
  arrange(-total) %>%
  head(41)

freedom %>%
  filter(country %in% x$country) %>%
  select(country, year, pr, cl) %>%
  pivot_longer(c("pr","cl")) %>%
  mutate(value = -value + 8) %>%
  group_by(country) %>%
  mutate(total = sum(value)) %>%
  ggplot(aes(value, fct_reorder2(country, value, total, .desc = FALSE), fill = name)) + geom_col() +
  labs(y = "", x = "Total Score", subtitle = "Countries that had best scores in 2020",
       title = "Best 30 Countries based on Civil Liberties and Political Rights",
       caption = "Total Score = Sum of scores from 1995 - 2020")
```


## Status
```{r}
freedom %>%
  mutate(pr = -pr +8,
         cl = -cl +8) %>%
  group_by(status) %>%
  summarize(mean_pr = mean(pr),
            mean_cl = mean(cl)) %>%
  pivot_longer(-status) %>%
  ggplot(aes(value, fct_reorder(status, value), fill = fct_reorder(status, value))) + geom_col() +
  facet_wrap(~name) + labs(y = "", x = "Average Value") 
```


### By Region
```{r}
freedom %>%
  mutate(status = fct_relevel(status,"NF", "PF", "F")) %>%
  ggplot(aes(fill = status, y = fct_reorder(region_name, status, function(.x) mean(.x == "F")))) + 
  geom_bar(position = "fill") + labs(y = "", x = "Proportion") + 
  scale_fill_manual(values = c("#B81D13", "#F5A33E", "#00C301")) +
  scale_x_continuous(labels = scales::label_percent())
```


## Region
```{r}
freedom %>%
  ggplot(aes(fill = is_ldc, y = fct_reorder(region_name, is_ldc, function(.x) mean(.x == "0")))) + 
  geom_bar(position = "fill") + 
  labs(y = "", x = "Percent", title = "The Proportion of Underdeveloped Countries per Region") + 
  scale_x_continuous(labels = scales::label_percent()) + 
  theme(legend.position = "", plot.title = element_text(hjust = 0.5))

table(freedom$is_ldc, freedom$region_name) %>%
  chisq.test()
```


## Is least developed and has perfect Cl and Pr
```{r}
freedom %>%
  filter(is_ldc == 1 & cl == 1 & pr == 1) %>%
  distinct(country, region_name)
```


# Multiple lm models of Pr or Cl by year for each country
```{r}
freedom_nest <- freedom %>%
  select(country, pr, cl, year) %>%
  nest(-country) %>%
  mutate(fitpr = map(data, ~ lm(pr ~ year, .x)),
         fitcl = map(data, ~ lm(cl ~ year, .x)),
         tidypr = map(fitpr, tidy),
         tidycl = map(fitcl, tidy)) %>%
  unnest(tidypr,tidycl)

freedom_nest %>%
  filter(term == "year") %>%
  select(country, estimate) %>%
  arrange(estimate)

freedom_nest %>%
  filter(term == "year") %>%
  select(country, estimate1) %>%
  arrange(estimate1)
```


## Plots of fastest decline in PR or CL
```{r}
gplot <- function(x,y){
  freedom %>%
    filter(country == {{x}}) %>%
    ggplot(aes(year, {{y}})) + geom_line() +
    geom_point()
}
gplot("Thailand", pr) + scale_y_reverse() + 
  labs(y = "Political Rights", title = "Thailand's Political Rights over the Years",
       subtitle = "On a scale of 1 to 7, 1 being the highest and 7 being the lowest")

gplot("South Sudan", cl) + scale_y_reverse(breaks = seq(5,7,1)) + 
  scale_x_continuous(breaks = seq(2011,2020,1)) + 
  labs(y = "Civil Liberties", title = "South Sudan's Civil Liberties over the Years",
       subtitle = "On a scale of 1 to 7, 1 being the highest and 7 being the lowest")
```


## Plots of fastest incline 
```{r}
gplot("Tunisia", pr) +
  scale_y_reverse(breaks = seq(1,7,1)) +
  labs(y = "Political Rights", title = "Tunisia's Political Rights over the Years",
       subtitle = "On a scale of 1 to 7, 1 being the highest and 7 being the lowest")

gplot("Bhutan", cl) + 
  scale_y_reverse() +
  labs(y = "Civil Liberties", title = "Bhutan's Civil Liberties over the Years",
       subtitle = "On a scale of 1 to 7, 1 being the highest and 7 being the lowest")
```



```{r}

```



