---
title: "Digital Publications"
author: "Matthew"
date: "4/5/2022"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, dpi = 600)
library(tidyverse)
library(tidymodels)
theme_set(theme_bw())
```


```{r}
news <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-04-05/news_orgs.csv')
news <- news %>% 
  select(-url) %>% 
  mutate(primary_language = 
           ifelse(primary_language == "Spanish, English", "Bilingual (Spanish & English)", primary_language))
skimr::skim(news)
```


# EDA
## Owner/Founder
```{r}
news %>% 
  group_by(state) %>% 
  summarize(n = mean(is_owner_founder == "Yes")) %>% 
  arrange(-n) %>% 
  head(10) %>% 
  ggplot(aes(n, fct_reorder(state,n))) + geom_col() +
  labs(y = "", x = "", title = "Proportion of Publications Where the Owner is the Founder by State")
```


```{r}
news %>% 
  filter(state == "MB") %>% 
  count(is_owner_founder)
```


```{r}
news %>% 
  filter(country != "United States") %>% 
  count(state, sort = TRUE)

news %>% 
  group_by(country) %>% 
  distinct(state) %>% 
  summarize(n = n())

news %>% 
  count(country, sort = TRUE)

news %>% count(primary_language, sort = TRUE)
```


## Primary Language
```{r}
news %>% 
  group_by(country) %>% 
  count(primary_language, sort = TRUE) %>% 
  filter(!is.na(primary_language)) %>% 
  ggplot(aes(n, fct_reorder(country, n), fill = fct_reorder(primary_language, n))) + 
  geom_col(position = position_dodge2(preserve = "single")) +
  scale_x_sqrt() + labs(y = "")

news %>% 
  filter(!is.na(primary_language)) %>% 
  ggplot(aes(year_founded, col = primary_language)) + geom_density()

news %>% 
  filter(!is.na(primary_language)) %>% 
  ggplot(aes(year_founded)) + geom_histogram() + facet_wrap(~primary_language)
```


## Tax Status
```{r}
news %>% 
  count(tax_status_current, sort = TRUE)

news %>% 
  filter(is.na(year_founded))

news %>% 
  filter(!is.na(tax_status_current), !is.na(year_founded)) %>% 
  group_by(year_founded) %>% 
  ggplot(aes(fill = year_founded, y = tax_status_current, group = year_founded)) + 
  geom_bar(position = "dodge") +
  scale_fill_viridis_c() + labs(y = "", x = "", title = "Number of Publications", fill = "Year")
```

