---
title: "Work"
author: "Matthew"
date: "4/5/2022"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
library(tidyverse)
theme_set(theme_bw())
```

# Q1
```{r}
scorecard <- read_csv("C:/Users/Matthew Hondrakis/Downloads/scorecard.csv")
scorecard <- scorecard %>% select(-1)
skimr::skim(scorecard)
```


```{r}
scorecard %>%
  keep(is.numeric) %>% 
  gather() %>% 
  ggplot(aes(value)) + geom_histogram() +
  facet_wrap(~key, scales = "free")
```


# Q2
```{r}
scorecard %>% 
  filter(firstgen > 0.6) %>% 
  select(name, type)
```


# Q3
```{r}
scorecard %>% 
  arrange(-cost) %>% 
  head(3) %>% 
  select(name,type)
```


# Q4
```{r}
scorecard %>% 
  group_by(type) %>% 
  summarize(mean = mean(satavg, na.rm = TRUE)) %>% 
  arrange(-mean)
```


# Q5
```{r}
scorecard %>% 
  filter(grepl("Princeton", name)) %>% 
  select(cost)


scorecard %>% 
  filter(type == "Private, nonprofit") %>% 
  summarize(prop = mean(cost > 66950, na.rm = TRUE))
```

