---
title: "Sports"
author: "Matthew"
date: "3/29/2022"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
library(tidyverse)
theme_set(theme_bw())
```


```{r}
sports <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-03-29/sports.csv')
sports <- sports %>% 
  rename(state = state_cd,
         sport = sports) %>% 
  rename_with( ~ gsub("_menwomen","",.x))
```


# EDA
```{r}
sports %>%
  keep(is.numeric) %>%
  select(-year) %>%
  gather() %>%
  ggplot(aes(value)) + geom_histogram() + facet_wrap(~key, scales = "free")
```


```{r}
sports %>%
  keep(is.numeric) %>%
  summarize_all(~ mean(is.na(.))) %>%
  select_if(. > 0) %>%
  gather() %>%
  arrange(-value)

sports %>%
  select(partic_coed_men) %>%
  count(partic_coed_men, sort = TRUE)
```


## Total Expenditure
```{r}
sports %>% 
  filter(!is.na(total_exp)) %>% 
  group_by(state) %>%
  summarize(n = sum(total_exp)/1e9) %>%
  arrange(-n) %>% 
  head(15) %>%
  ggplot(aes(n, fct_reorder(state,n))) + geom_col() +
  labs(y = "", x = "Total Expenditure (in millions)", title = "Total Spent by State") +
  theme(plot.title = element_text(hjust = 0.5))
```


```{r}
(names <- sports %>%
  filter(!is.na(state)) %>%
  select(state, sport, total_exp) %>%
  mutate(sport = str_replace(sport, ", Indoor|, Outdoor|, X-Country", "")) %>% 
  group_by(state) %>% 
  summarize(n = sum(total_exp, na.rm = TRUE)) %>% 
  arrange(-n) %>%
  pull(state))

sports %>%
  filter(!is.na(total_exp) & state %in% names[1:10]) %>%
  select(sport, state, total_exp) %>%
  mutate(sport = str_replace(sport, ", Indoor|, Outdoor|, X-Country", "")) %>% 
  group_by(state, sport) %>% 
  summarize(n = sum(total_exp)/1e9) %>%
  top_n(5, n) %>% 
  ggplot(aes(n, fct_reorder(state, n, .fun = sum), fill = sport)) +
  geom_col() + 
  labs(y = "", x = "Total Spent (in billions)", fill = "", title = "Top 5 Sports for each State",
                    subtitle = "From 2015 to 2019", 
       caption = "The sum is only accounting for the top 5 sports spent in each state") +
  theme(plot.title = element_text(hjust = 0.5), plot.subtitle = element_text(hjust = 0.5)) + 
  scale_x_continuous(labels = scales::dollar)
```


```{r}
sports %>% 
  filter(state == "TX" & !is.na(total_exp)) %>% 
  group_by(sport) %>% 
  summarize(n = sum(total_exp)) %>%
  arrange(-n)
```


## Sex Differences
```{r}
sports %>% 
  select(sport, exp_men, exp_women, total_exp) %>%
  mutate(exp_men = ifelse(is.na(exp_men), 0, exp_men),
         exp_women = ifelse(is.na(exp_women), 0, exp_women)) %>% 
  summarize(sum = exp_men + exp_women,
            total_exp) %>% 
  summarize(correct = mean(sum == total_exp, na.rm = TRUE),
            missing = mean(is.na(sum) | is.na(total_exp)))
```


```{r}
sports %>% 
  select(state, exp_men, exp_women) %>% 
  filter(!is.na(exp_men) & !is.na(exp_women)) %>% 
  group_by(state) %>% 
  summarize(n = sum(exp_men - exp_women)/1e6) %>%
  filter(!is.na(state)) %>% 
  ggplot(aes(fct_reorder(state,n),n)) + geom_col() +
  labs(y = "", x = "", title = "Amount Spent More on Men by State",
       subtitle = "In millions") + 
  scale_y_continuous(labels = scales::dollar) +
  theme(axis.text.x = element_text(angle = 90))
```


```{r}
sports %>% 
  select(state, exp_men, exp_women, year) %>% 
  filter(!is.na(exp_men) & !is.na(exp_women)) %>% 
  group_by(state, year) %>% 
  summarize(n = sum(exp_men - exp_women)/1e6) %>%
  filter(!is.na(state)) %>% 
  ggplot(aes(fct_reorder(state,n), n, fill = year)) + geom_col() +
  labs(y = "", x = "", title = "Amount Spent More on Men by State",
       subtitle = "In millions") + 
  scale_y_continuous(labels = scales::dollar) +
  theme(axis.text.x = element_text(angle = 90))
```


```{r}
sports %>%
  select(rev_men, exp_men) %>% 
  drop_na() %>% 
  ggplot(aes(rev_men, exp_men)) + geom_point(alpha = 0.2) 

sports %>% 
  select(rev_women, exp_women) %>% 
  drop_na() %>% 
  ggplot(aes(rev_women, exp_women)) + geom_point(alpha = 0.2) 
```


# Sectors
```{r}
sports %>% 
  filter(!is.na(sector_name) & !is.na(total_exp)) %>% 
  group_by(sector_name) %>% 
  summarize(n = sum(total_exp)/1e6) %>% 
  ggplot(aes(n, fct_reorder(sector_name, n, max))) + geom_col() +
  scale_x_log10(labels = scales::dollar) + labs(y = "", x = "Total Spent in millions")
```


```{r}
sports %>%
  filter(state %in% names) %>%
  group_by(state, sector_name) %>% 
  summarize(n = sum(total_exp, na.rm = TRUE)/1e6) %>% 
  filter(state %in% c("TX","NY","CA","FL","PA","AL","MI","OH")) %>%
  top_n(3, n) %>% 
  ggplot(aes(n, fct_reorder(state, n, max), fill = sector_name)) +
  geom_col(position = "dodge") + 
  labs(y = "", x = "Total Spent (in millions)", fill = "",
       title = "State spending by Sector") + 
  scale_x_continuous(labels = scales::dollar)
```


## Proportion of States where Public expending is more than Private
```{r}
sports %>%
  filter(sector_name %in% c("Public, 4-year or above", "Private nonprofit, 4-year or above")) %>% 
  group_by(state, sector_name) %>% 
  summarize(t = sum(total_exp, na.rm = TRUE)) %>% 
  pivot_wider(names_from = sector_name, values_from = t) %>%
  rename(public = "Public, 4-year or above", private = "Private nonprofit, 4-year or above") %>% 
  ungroup() %>% 
  summarize(prop = mean(public > private, na.rm = TRUE))
```


```{r}
sports %>%
  filter(!is.na(state)) %>% 
  group_by(state, sector_name) %>% 
  mutate(sector_name = ifelse(str_detect(sector_name, "^Public"), "Public", "Private")) %>% 
  summarize(n = sum(total_exp, na.rm = TRUE)/1e6) %>% 
  pivot_wider(names_from = sector_name, values_from = n) %>% 
  ungroup() %>% 
  summarize(prop = mean(Public > Private, na.rm = TRUE))
```





