---
title: "Eurovision"
author: "Matthew"
date: "5/16/2022"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, dpi = 500)
library(tidyverse)
library(scales)
theme_set(theme_bw())
```


```{r}
eurovision <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-05-17/eurovision.csv')

```



```{r}
head(eurovision)

eurovision <- eurovision %>% 
  select(!contains("url"))

skimr::skim(eurovision)
```

# EDA
```{r}
eurovision %>% 
  group_by(artist_country) %>% 
  summarize(total_first = sum(rank == 1, na.rm = TRUE)) %>% 
  arrange(-total_first)


eurovision %>% 
  group_by(artist_country) %>% 
  summarize(total_wins = sum(winner)) %>% 
  arrange(-total_wins)

eurovision %>% 
  group_by(artist_country) %>% 
  summarize(mean_rank = mean(rank, na.rm = TRUE)) %>% 
  arrange(mean_rank)

eurovision %>% 
  filter(winner == TRUE) %>% 
  distinct(artist_country, year) %>% 
  count(artist_country, sort = TRUE)
```



```{r}
eurovision %>% 
  filter(artist_country == "Greece" & winner == TRUE) %>% 
  View

eurovision %>% 
  arrange(-year, -total_points) %>% 
  select(artist_country, total_points, year, winner) %>% 
  View
```


```{r}
eurovision %>% 
  count(artist, sort = TRUE) %>% 
  inner_join(eurovision %>% 
               distinct(artist_country, artist) %>% 
               select(artist, artist_country)) %>% 
  arrange(-n, artist_country)
```


```{r}
eurovision %>% 
  filter(rank == parse_number(rank_ordinal))

eurovision %>% 
  filter(is.na(rank_ordinal))
```




```{r}
eurotidy <- eurovision %>% 
  select(year, total_points, artist_country) %>% 
  nest(-artist_country) %>% 
  mutate(model = map(data, ~ lm(total_points ~ year,.)),
         tidy = map(model, broom::tidy)) %>% 
  unnest(tidy) %>% 
  filter(term == "year") %>% 
  arrange(-abs(estimate))

x <- eurotidy %>% 
  head(10) %>% 
  pull(artist_country)

eurovision %>% 
  filter(artist_country %in% x) %>% 
  ggplot(aes(year, total_points)) + geom_line() + geom_smooth(method = "lm", se = FALSE) +
  geom_point() +
  facet_wrap(~artist_country)
```


```{r}
(euro_summary <-  eurovision %>% 
  group_by(artist_country) %>% 
  summarize(diff = total_points[year == max(year)] - total_points[year == min(year)]) %>% 
  arrange(-abs(diff)))

y <- euro_summary %>% 
  head(10) %>% 
  pull(artist_country)

eurovision %>% 
  filter(artist_country %in% y) %>% 
  ggplot(aes(year, total_points)) + geom_line() + geom_smooth(method = "lm", se = FALSE) +
  geom_point() + 
  facet_wrap(~artist_country)
```


