---
title: "Drought"
author: "Matthew"
date: '2022-06-14'
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, dpi = 500)
library(tidyverse)
library(patchwork)
library(scales)
library(lubridate)
theme_set(theme_bw())
```


# Read and Process
```{r}
drought <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-06-14/drought.csv')
drought_fips <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-06-14/drought-fips.csv')

drought <- drought %>% 
  select(-"-9",-"0")

drought <- drought %>% 
  mutate(DATE = gsub('d_',"", DATE)) %>% 
  rename(date = DATE)

drought <- drought %>% 
  mutate(date = as.Date(date, format = "%Y%m%d"),   #convert to date
         state = str_to_title(state))               #capitalize first letter
```


# EDA
```{r}
drought %>% 
  keep(is.numeric) %>% 
  gather() %>% 
  ggplot(aes(value)) + geom_histogram() + facet_wrap(~key)
```



```{r}
drought %>% 
  arrange(-D4) %>% 
  select(date, D4, state)

drought %>% 
  group_by(state) %>% 
  summarize_if(is.numeric, mean) %>% 
  arrange(-D4)
```



## Comparison of D4 and w4
```{r}
drought %>% 
  ggplot(aes(W4, D4)) + geom_point(alpha = 0.2) +
  labs(title = "Inverse Relationship with D4 and W4")
```



## Drought by State
```{r}
drought_fips %>% 
  group_by(State) %>% 
  summarize(m = median(DSCI)) %>% 
  arrange(-m) %>% 
  head(15) %>% 
  ggplot(aes(m, fct_reorder(State,m))) + geom_col(color = "black", fill = "lightblue") +
  labs(y = "", x = "Median Drought", 
       title = "Top 15 States with Most Severe Drought", subtitle = "Drought Scale goes from 0 to 500")  +
  theme(plot.title = element_text(hjust = 0.5), 
        plot.subtitle = element_text(hjust = 0.5))
```



```{r}
avg_drought <- drought_fips %>% 
  group_by(date) %>% 
  summarize(drought = mean(DSCI)) %>% 
  mutate(month = month(date, label = TRUE),
         season = case_when(grepl("Dec|Jan|Feb", month) ~ "Winter",
                            grepl("Mar|Apr|May", month) ~ "Spring",
                            grepl("Jun|Jul|Aug", month) ~ "Summer",
                            grepl("Sep|Oct|Nov", month) ~ "Fall"))

avg_drought %>% 
  ggplot(aes(date, drought)) + geom_line() + 
  geom_point(aes(color = season)) + facet_wrap(~year(date), scales = "free")

avg_drought %>% 
  ggplot(aes(date, drought)) + geom_line() + 
  geom_point(aes(color = season))

(avg_drought %>% 
  ggplot(aes(drought, fct_rev(month), fill = season)) + geom_col() +
  labs(y = "", fill = "")) /
(avg_drought %>% 
   ggplot(aes(drought, season, fill = season)) + geom_boxplot() +
   labs(y = "", fill = "") + theme(legend.position = "none")) + plot_layout(guides = 'collect')

anova(aov(drought ~ season, avg_drought))
```


# Fitting an AR model on the timeseries
```{r}
library(astsa)
timeseries <- ts(avg_drought$drought, start = c(2000, 1), freq = 52)

plot(timeseries)

acf2(timeseries)

sarima(timeseries, 3, 0, 0)

sarima.for(timeseries, 52, 3, 0, 0)
title(main = "One year forcast")
```


