---
title: "San Francisco Rentals"
author: "Matthew"
date: '2022-07-06'
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, dpi = 500)
library(tidyverse)
library(patchwork)
library(scales)
library(lubridate)
theme_set(theme_bw())
```



```{r}
rent <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-07-05/rent.csv')
permits <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-07-05/sf_permits.csv')
new_construction <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-07-05/new_construction.csv')
```



```{r}
skimr::skim(rent)
```
 


```{r}
rent %>% 
  keep(is.numeric) %>% 
  gather() %>% 
  ggplot(aes(value)) + geom_histogram() + facet_wrap(~key, scales = "free")
```




```{r}
(rent %>% 
  group_by(year) %>% 
  summarize(price = median(price)) %>% 
  ggplot(aes(year, price)) + geom_line()) /
(rent %>% 
   group_by(year) %>% 
   ggplot(aes(year, price, group = year)) + geom_boxplot())
```



```{r}
rent %>% 
  filter(!is.na(county)) %>% 
  group_by(county) %>% 
  mutate(med = median(price),
         county = str_to_title(county)) %>% 
  ggplot(aes(fct_reorder(county, med), price)) + geom_boxplot()
```



```{r}
lm(price ~ 0 + ., 
   rent %>% 
    keep(is.numeric) %>% 
    drop_na()) %>% broom::tidy() %>% 
  arrange(-abs(estimate))
```



```{r}
hoods <- rent %>% 
  group_by(nhood) %>%
  mutate(medianp = median(price)) %>%
  distinct(medianp) %>% 
  arrange(-medianp) %>% 
  head(10) %>% pull(nhood)

rent %>% 
  filter(nhood %in% hoods) %>% 
  ggplot(aes(price, fct_reorder(nhood, price, median))) + geom_boxplot()
```



```{r}
rent %>% 
  ggplot(aes(lon, lat, color = log(price))) + geom_point() +
  xlim(-125, -120) + ylim(36, 39)

sfmap <- map_data("county", region = "California")

sfmap_joined <- rent %>% 
  group_by(county) %>% 
  summarize(price = median(price)) %>% 
  left_join(sfmap, by = c("county" = "subregion"))
```



```{r}
sfmap_joined %>% 
  ggplot(aes(long, lat, group = group, fill = price)) + geom_polygon()
```



```{r}
rent %>% 
  keep(is.numeric) %>% 
  select(-date, -lat, -lon) %>% 
  pivot_longer(-price) %>% 
  ggplot(aes(value, price)) + geom_point() + facet_wrap(~name, scales = "free")
```



