---
title: "Artists"
author: "Matthew"
date: "2022-09-27"
output: 
  github_document:
    toc: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, dpi = 500)
library(tidyverse)
library(scales)
theme_set(theme_bw())
```


```{r}
artists <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-09-27/artists.csv')
```

# EDA
```{r}
artists %>% 
  head(15)

skimr::skim(artists)
```


Is artists share = artists_n/all_workers_n?
```{r}
artists %>% 
  mutate(new = artists_n/all_workers_n) %>% 
  select(artists_share, new)

artists %>% 
  mutate(new = artists_n/all_workers_n) %>% 
  select(artists_share, new) %>% 
  summarize(mean(artists_share == new, na.rm = TRUE))
```


```{r}
artists %>% 
  mutate(new = artists_n/all_workers_n) %>% 
  filter(new != artists_share) %>% 
  select(-location_quotient)

artists %>% 
  mutate(new = artists_n/all_workers_n) %>% 
  filter(new != artists_share) %>% 
  summarize(difference = sum(artists_share - new),
            avg = mean(artists_share - new, na.rm = TRUE))
```
It appears there may be a minor difference in artists_share and artists_n/all_workers_n, but its most likely a computational error.


## Summarize Function
```{r}
summarize_fun <- function(x, y = NULL){
  artists %>% 
    group_by({{x}}, {{y}}) %>% 
    summarize(sum = sum(artists_n, na.rm = TRUE))
}
```


```{r}
summarize_fun(race, type) %>% 
  filter(type == "Actors") %>% 
  ungroup() %>% 
  ggplot(aes(sum, fct_reorder(race, sum))) + geom_col(color = "black", fill = "lightblue") +
  labs(y = "", x = "Total", title = "Artists in the USA by Race")
```





