---
title: "Bigfoot"
author: "Matthew"
date: "2022-09-13"
output: 
  github_document:
    toc: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, dpi = 500)
library(tidyverse)
library(patchwork)
library(scales)
library(tidytext)
theme_set(theme_bw())
```


```{r, include = FALSE}
bigfoot <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-09-13/bigfoot.csv')
```

# EDA
```{r}
skimr::skim(bigfoot)
```


```{r}
bigfoot %>% 
  keep(is.numeric) %>% 
  gather() %>% 
  ggplot(aes(value)) + geom_histogram() +
  facet_wrap(~key, scales = "free")
```


## Text Analysis
```{r}
bigfoot %>% 
  unnest_tokens(word, summary) %>% 
  anti_join(stop_words) %>%
  group_by(classification) %>% 
  count(word, sort = TRUE) %>% 
  filter(!is.na(word)) %>% 
  head(15) %>% 
  mutate(word = fct_reorder(word, n)) %>% 
  ggplot(aes(n, word)) + geom_col(color = "black", position = position_dodge2(preserve = "single"), aes(fill = classification)) + 
  ggtitle(str_to_title("Most common words describing the day"))
```


```{r}
bigfoot %>% 
  unnest_tokens(word, observed) %>% 
  anti_join(stop_words) %>%
  group_by(classification) %>% 
  count(word, sort = TRUE) %>% 
  filter(!is.na(word)) %>% 
  head(20) %>% 
  ungroup() %>% 
  mutate(word = fct_reorder(word, n, sum)) %>% 
  ggplot(aes(n, word)) + geom_col(color = "black", position = position_dodge2(preserve = "single"), aes(fill = classification)) + 
  ggtitle(str_to_title("Most common words describing the story"))
```


```{r}
bigfoot %>% 
  unnest_tokens(word, title) %>% 
  anti_join(stop_words) %>%
  group_by(classification) %>% 
  count(word, sort = TRUE) %>% 
  filter(!is.na(word)) %>% 
  head(20) %>% 
  ungroup() %>% 
  mutate(word = fct_reorder(word, n, sum)) %>% 
  ggplot(aes(n, word)) + geom_col(color = "black", position = position_dodge2(preserve = "single"), aes(fill = classification)) + 
  ggtitle(str_to_title("Most common words describing the story"))
```


# Model

## Preprocess
```{r}
library(tidymodels)
library(textrecipes)
set.seed(123)

bigfoot_split <- initial_split(bigfoot %>%
                                 rename(class = classification) %>% 
                                 filter(class != "Class C", !is.na(title)) %>%
                                 mutate(title = str_remove_all(title, ".*\\:"),
                                        class = as.factor(class)),
                               strata = class)
```


## Fitting
```{r}
glm_workflow <- 
  recipe(formula = class ~ title, data = training(bigfoot_split)) %>% 
  step_tokenize(title) %>%
  step_stopwords(title, custom_stopword_source = stop_words) %>% 
  step_tokenfilter(title, max_tokens = 1e2) %>% 
  step_tfidf(title) %>% 
  workflow(logistic_reg(mode = "classification", engine = "glm"))


glm_fit <- glm_workflow %>% last_fit(bigfoot_split)
```


## Metrics
```{r}
glm_fit %>% 
  collect_metrics()

glm_fit %>% 
  collect_predictions() %>% 
  roc_curve(as.factor(class), `.pred_Class A`) %>% 
  autoplot()
```



```{r}
glm_fit %>% 
  extract_fit_parsnip() %>% 
  broom::tidy() %>% 
  filter(p.value < 0.05 & term != "(Intercept)") %>% 
  mutate(term = str_remove(term, "tfidf_title_")) %>% 
  slice_max(abs(estimate), n = 20) %>% 
  ggplot(aes(abs(estimate), fct_reorder(term, abs(estimate)), fill = ifelse(estimate < 0, "A", "B"))) + geom_col(color = "black") +
  scale_fill_discrete(direction = -1) +
  labs(fill = "Class", y = "", title = str_to_title("Importance of words in predicting class"))
```

