---
title: "Art History"
author: "Matthew"
date: "2023-01-17"
output: 
  github_document:
    toc: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, dpi = 500)
library(tidyverse)
library(scales)
library(patchwork)
theme_set(theme_bw())
theme_update(plot.title = element_text(hjust = 0.5))
```

```{r}
artist <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-01-17/artists.csv')

artist <- artist %>% 
  rename_with(~gsub("artist_", "", .x))
```

# Data Cleaning

## Missing Values

```{r}
skimr::skim(artist) %>% select(skim_type, skim_variable, n_missing)
```

## Counts

```{r}
artist %>% 
  count(race, sort = TRUE)
```

*race* has a string called N/A, this should be replaced with NA values as missing data.

```{r}
artist %>% 
  mutate(race = ifelse(race == "N/A", NA, race))
```

# Exploratory Data Analysis

### Race

```{r}
artist %>% 
  group_by(ethnicity) %>% 
  count(race, sort = TRUE) %>% 
  drop_na() %>% 
  ggplot(aes(n, fct_reorder(race, n, sum))) +
  geom_col(color = "black", aes(fill = fct_rev(ethnicity))) +
  scale_x_log10() +
  labs(y = "", x = "", fill = "")
```

```{r}
artist %>% 
  group_by(year) %>% 
  count(race) %>% 
  ggplot(aes(year, n, color = race)) +
  geom_line()

artist %>% 
  drop_na() %>% 
  ggplot(aes(year, fill = race, color = race)) +
  geom_density(alpha = 0.5)
```
