---
title: "Company Reputation Poll"
author: "Matthew Hondrakis"
date: '2022-05-31'
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, dpi = 500)
library(tidyverse)
library(patchwork)
theme_set(theme_bw())
```


```{r}
poll <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-05-31/poll.csv')
reputation <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-05-31/reputation.csv')

```

```{r}
poll %>% 
  distinct(industry)

poll %>% 
  ggplot(aes(`2022_rq`, fct_reorder(industry, `2022_rq`))) + geom_boxplot()
```


```{r}
x <- poll %>% 
  group_by(company) %>% 
  summarize(m = mean(`2022_rank`)) %>% 
  arrange(desc(m)) %>% 
  head(20) %>% 
  pull(company)

poll %>% 
  group_by(company) %>% 
  summarize(m = mean(`2022_rank`)) %>% 
  arrange(desc(m)) %>% 
  head(20) %>% 
  ggplot(aes(m, fct_reorder(company, m))) + geom_col() +
  labs(y = "")

reputation %>% 
  filter(company %in% x) %>% 
  group_by(name) %>% 
  ggplot(aes(score, fct_reorder(name, score))) + 
  facet_wrap(~company) +
  geom_boxplot() + theme(legend.position = "none")
```


```{r}
(reputation %>% 
  group_by(name) %>% 
  summarize(m = mean(score)) %>% 
  ggplot(aes(m, fct_reorder(name,m))) + geom_col() +
  xlim(0,85) + labs(y = "")) /
(reputation %>% 
  ggplot(aes(score, fct_reorder(name, score))) + geom_boxplot() +
  xlim(0, 85) + labs(y = ""))
```



```{r}
reputation %>% 
  arrange(-score) %>% 
  select(4,5)
```


```{r}
reputation %>% 
  ggplot(aes(score, rank)) + geom_point() +
  facet_wrap(vars(name))
```



```{r}
names <- poll %>% 
  arrange(-`2022_rq`) %>%
  distinct(company) %>% 
  head(20) %>% 
  pull(company)
```


```{r}
poll %>% 
  filter(company %in% names) %>% 
  ggplot(aes(`2022_rq`, fct_reorder(company, `2022_rq`), 
             fill = -`2022_rank`)) + geom_col() + labs(y = "", x = "") +
  theme(legend.position = "none")

```

