---
title: "Crossword Puzzle"
author: "Matthew"
date: "4/18/2022"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, dpi = 500)
library(tidyverse)
library(tidytext)
library(patchwork)
library(lubridate)
theme_set(theme_bw())
```


```{r}
big_dave <- 
  read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-04-19/big_dave.csv')
times <- 
  read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-04-19/times.csv')

puzzles <- big_dave %>% 
  bind_rows(times)
```


# EDA
```{r}
puzzles %>% 
  group_by(source) %>% 
  count(definition, sort = TRUE)

puzzles %>%
  group_by(source) %>% 
  count(puzzle_name, sort = TRUE)

puzzles %>% 
  group_by(source) %>% 
  count(clue_number, sort = TRUE)
```



```{r}
puzzles %>% 
  filter(!is.na(definition)) %>% 
  filter(definition == "Bird") %>% 
  group_by(year = year(puzzle_date)) %>% 
  summarize(n = n()) %>% 
  ggplot(aes(year, n)) + geom_line()

puzzles %>% 
  filter(!is.na(definition)) %>% 
  filter(definition %in% pull(puzzles %>% count(definition, sort = TRUE) %>% head(10), definition)) %>% 
  group_by(year = year(puzzle_date), definition) %>% 
  ggplot(aes(year, color = definition)) + geom_density() +
  scale_x_continuous(breaks = seq(2010,2022,2)) +
  labs(title = "Yearly Proportion of 10 most common definitions", y = "", x = "")
```


## Number of words per Month
```{r}
puzzles %>% 
  unnest_tokens(word, definition) %>% 
  group_by(month = month(puzzle_date, label = TRUE)) %>% 
  filter(!is.na(month)) %>% 
  summarize(n = n()) %>% 
  arrange(-n) %>% 
  ggplot(aes(month, n, group = 1)) + geom_line() +
  labs(title = "Total Number of Words in the definition per month")

puzzles %>% 
  unnest_tokens(word, clue) %>% 
  group_by(month = month(puzzle_date, label = TRUE)) %>% 
  filter(!is.na(month)) %>% 
  summarize(n = n()) %>% 
  ggplot(aes(month, n, group = 1)) + geom_line() +
  labs(title = "Total number of words in clues per month")
```


## Number of words per Week
```{r}
week_count <- puzzles %>%
  group_by(week = wday(puzzle_date, label = TRUE)) %>% 
  filter(!is.na(week)) %>% 
  summarize(count = n())

p <- puzzles %>% 
  unnest_tokens(word, clue) %>% 
  group_by(week = wday(puzzle_date, label = TRUE)) %>% 
  filter(!is.na(week)) %>% 
  summarize(n = n()) %>% 
  inner_join(week_count) %>% 
  ggplot(aes(week, n/count, group = 1)) + labs(y = "", x = "")

(p + geom_line()) +
  (p + geom_col(aes(fill = week)) + scale_fill_discrete(guide = "none")) + 
  plot_annotation(title = "Average Words in Clues per Weekday",
                  theme = theme(plot.title = element_text(hjust = 0.5)))
```



```{r}
puzzles %>% 
  mutate(week = wday(puzzle_date, label = TRUE)) %>% 
  select(puzzle_date,week, source) %>% 
  group_by(source) %>% 
  summarize(mean(is.na(week)))

puzzles %>% 
  mutate(week = wday(puzzle_date, label = TRUE)) %>% 
  filter(is.na(week)) %>% 
  select(puzzle_date, week)
```
 
 