---
title: "Ravelry Yarn"
author: "Matthew"
date: "2022-10-11"
output: 
  github_document:
    toc: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, dpi = 500)
library(tidyverse)
library(scales)
library(tidymodels)
theme_set(theme_bw())
```

```{r}
yarn <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-10-11/yarn.csv')
```

```{r}
skimr::skim(yarn)
```

# EDA
## Correlations
```{r}
yarn %>% 
  keep(is.numeric) %>% 
  select(-thread_size, -rating_total) %>% 
  cor(use = "complete.obs", method = "spearman") %>% 
  as.data.frame() %>% 
  rownames_to_column(var = "item1") %>% 
  gather(key = item2, value = corr, -item1) %>% 
  filter(item1 > item2) %>% 
  arrange(-abs(corr))
```

```{r}
yarn %>% 
  filter(!is.na(discontinued)) %>% 
  ggplot(aes(rating_average, fill = discontinued)) + geom_density(alpha = 0.5)
```

## Logistic regression model 

By creating a logistic regression model, you can get a quick look into what helps predict whether an item was discontinued using all numeric predictors. 

```{r}
mod_data <- yarn %>% 
  select(contains("discontinued"), where(is.numeric)) %>% 
  select(-thread_size, -rating_total) %>% 
  mutate(discontinued = factor(discontinued))

quickmod <- glm(discontinued ~., mod_data, family = binomial())

summary(quickmod)
```

```{r}
mod_data %>% 
  mutate(predictions = 1 - predict(quickmod, mod_data, type = "response")) %>% 
  roc_curve(discontinued, predictions) %>% 
  autoplot()

mod_data %>% 
  mutate(predictions = 1 - predict(quickmod, mod_data, type = "response")) %>% 
  roc_auc(discontinued, predictions)
```

```{r}
broom::tidy(quickmod) %>% 
  filter(p.value > 0.05)
```

## Texture
### 20 Most Common Textures
```{r}
yarn %>% 
  mutate(texture = tolower(texture)) %>% 
  count(texture, sort = TRUE)

yarn %>% 
  mutate(texture = tolower(texture)) %>% 
  filter(!is.na(texture)) %>% 
  mutate(texture = ifelse(texture == "bouclé", "boucle", texture),
         texture = fct_lump(texture, 20)) %>% 
  filter(texture != "Other") %>% 
  group_by(texture) %>% 
  summarize(avg = mean(discontinued == TRUE, na.rm = TRUE)) %>% 
  ggplot(aes(avg, fct_reorder(texture, avg))) +
  geom_col(color = "black", fill = "skyblue2") +
  labs(y = "", x = "", title = "Percent of Discontinued Items by Texture") +
  scale_x_continuous(label = percent_format()) +
  theme(plot.title = element_text(hjust = 0.5))
```

# Tidymodels
## Splits
```{r}
set.seed(123)
split <- initial_split(yarn %>% 
                         mutate(discontinued = as.factor(discontinued),
                                texture = tolower(texture),
                                texture = ifelse(texture == "bouclé", "boucle", texture),
                                texture = fct_lump(texture, 20)), strata = discontinued)

train <- training(split)
test <- testing(split)
```

## Model and Recipe

```{r}
mod <- logistic_reg(mode = "classification", engine = "glm")

rec <- recipe(discontinued ~ min_gauge + rating_average + rating_count + texture, train) %>% 
  step_novel(all_nominal_predictors()) %>% 
  step_zv(all_predictors()) %>% 
  step_normalize(all_numeric_predictors()) %>% 
  step_impute_mean(all_numeric_predictors())

wkfl_fit <- workflow() %>% 
  add_recipe(rec) %>% 
  add_model(mod) %>% 
  fit(train)
```

## Metrics

```{r}
test %>% 
  mutate(predict(wkfl_fit, test, type = "prob")) %>% 
  roc_curve(discontinued, `.pred_FALSE`) %>% 
  autoplot()

test %>% 
  mutate(predict(wkfl_fit, test, type = "prob")) %>% 
  roc_auc(discontinued, `.pred_FALSE`) 
```

