---
title: "Open Psychometrics"
author: "Matthew"
date: "2022-08-16"
output: 
  github_document:
    toc: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, dpi = 500)
library(tidyverse)
library(patchwork)
library(scales)
library(rvest)
library(ggimage)
theme_set(theme_bw())
```


```{r}
characters <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-08-16/characters.csv')

head(characters)

skimr::skim(characters)
```


```{r}
characters %>% 
  group_by(uni_name) %>% 
  summarize(m = mean(notability)) %>% 
  arrange(-m) %>%
  mutate(uni_name = fct_reorder(uni_name, m)) %>% 
  slice(c(1:10, 91:100)) %>% 
  ggplot(aes(m, uni_name, fill = 60 > m)) + geom_col(color = "black") +
  labs(y = "", x = "Average Notability", title = "Average Notability of Characters in Shows") +
  theme(plot.title = element_text(hjust = 0.5), legend.position = "none") + 
  scale_fill_manual(values = c("lightblue", "darkred"))
```



# Web-scraping (code derived from Tanya Shapiro)
```{r eval=FALSE, include=FALSE}
#scrape personality details
get_personality<-function(url){
  html = url%>%read_html()
  
  character = html%>%
    html_elements("h3")%>%
    head(1)%>%
    html_text()
  
  data= html%>%
    html_elements("table.zui-table")%>%
    html_table()%>%
    .[[1]]
  
  names(data)=c("item","avg_rating","rank","rating_sd","number_ratings")
  data$character = str_replace(character," Descriptive Personality Statistics","")
  
  data
}

base_url<-'https://openpsychometrics.org/tests/characters/stats/GOT/'

got_profiles<-data.frame()
#create a loop to scrape all characters, there are a total of 15 characters profiled, use range 1:16
for(i in 1:31){
  url<-paste0(base_url, i)
  temp_data<-get_personality(url)
  got_profiles<-rbind(got_profiles,temp_data)
}

write_csv(got_profiles, "08-16-22/got_profiles.csv")
```


```{r}
got_profiles <- read_csv("got_profiles.csv")
```


```{r}
got_profiles <- got_profiles %>%  
    left_join(characters %>% select(character = name, image_link))
```



# Game of Thrones Characters

## Trait Plot Function
```{r}
gplot <- function(x){
  got_profiles %>% 
    filter(str_detect(trait, {{x}})) %>% 
    mutate(character = fct_reorder(character, avg_rating)) %>% 
    ggplot(aes(avg_rating, character)) + geom_col(color = "black", fill = "lightblue") +
    geom_image(aes(image = image_link, x = 5), size = 0.03) + 
    geom_errorbarh(aes(xmax = avg_rating+rating_sd, xmin = avg_rating-rating_sd, height = 0.3)) +
    scale_x_continuous(label = percent_format(scale = 1))
}
```


## Plots
```{r}
gplot("main character") + labs(y = "", x = "", title = "Game of Thrones Characters",
                               subtitle = "Main Character Rating")


gplot("high IQ") + labs(y = "", x = "", title = "Game of Thrones Characters", 
                        subtitle = "'High IQ' Average Rating")

gplot("intense") + labs(y = "", x = "", title = "Game of Thrones Characters", 
                        subtitle = "Intense Average Rating")


gplot("practical") + labs(y = "", x = "", title = "Game of Thrones Characters", 
                        subtitle = "Intense Average Rating")
```



# Simpsons
```{r, eval=FALSE}
#scrape personality details
get_personality<-function(url){
  html = url%>%read_html()
  
  character = html%>%
    html_elements("h3")%>%
    head(1)%>%
    html_text()
  
  data= html%>%
    html_elements("table.zui-table")%>%
    html_table()%>%
    .[[1]]
  
  names(data)=c("item","avg_rating","rank","rating_sd","number_ratings")
  data$character = str_replace(character," Descriptive Personality Statistics","")
  
  data
}

base_url<-'https://openpsychometrics.org/tests/characters/stats/S/'

simpsons_profiles<-data.frame()
#create a loop to scrape all characters, there are a total of 15 characters profiled, use range 1:16
for(i in 1:16){
  url<-paste0(base_url, i)
  temp_data<-get_personality(url)
  simpsons_profiles<-rbind(simpsons_profiles,temp_data)
}

write_csv(simpsons_profiles, "08-16-22/simpsons_profiles.csv")
```


```{r}
simpsons_profiles <- read_csv("simpsons_profiles.csv")
```


```{r}
simpsons_profiles <- simpsons_profiles %>% 
  left_join(characters %>% select(character = name, image_link))

simpsons_profiles %>% 
  distinct(item)

mutated_items <- simpsons_profiles %>% 
  mutate(item = str_replace(item, "\\(.*","")) %>% 
  pull(item)
```


```{r}
gplot2 <- function(data, x){
  data %>% 
    filter(str_detect(item, {{x}})) %>%  
    mutate(character = fct_reorder(character, avg_rating)) %>% 
    ggplot(aes(avg_rating, character)) + geom_col(color = "black", fill = "lightblue") +
    geom_image(aes(image = image_link, x = 5)) + 
    geom_errorbarh(aes(xmax = avg_rating+rating_sd, xmin = avg_rating-rating_sd, height = 0.3)) +
    scale_x_continuous(label = percent_format(scale = 1)) + labs(title = str_to_title(x))
}
```


## Plot 2 random traits
```{r}
names <- sample(mutated_items, 2)

for(i in 1:2){
  x <- names[i]
  if(i == 1){
    plot1 <- gplot2(simpsons_profiles, x)
  } else{
    plot2 <- gplot2(simpsons_profiles, x)}
}

plot1 + plot2
```
