---
title: "Indoor Pollution"
author: "Matthew"
date: "4/11/2022"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, dpi = 600)
library(tidyverse)
theme_set(theme_bw())
```


```{r}
indoor_pollution <- 
  read_csv(
    'https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-04-12/indoor_pollution.csv')

fuel_access <- 
  read_csv(
    'https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-04-12/fuel_gdp.csv')
```



```{r}
fuel_access <- fuel_access %>% 
  rename_with(tolower) %>% 
  rename(access_pct = "access to clean fuels and technologies for cooking (% of population)") %>% 
  rename(gdp = `gdp per capita, ppp (constant 2017 international $)`) %>% 
  rename(population = `population (historical estimates)`)

indoor_pollution <- indoor_pollution %>% 
  rename(deaths_pct = "Deaths - Cause: All causes - Risk: Household air pollution from solid fuels - Sex: Both - Age: Age-standardized (Percent)") %>% 
  rename_with(tolower)

joined_data <- indoor_pollution %>% 
  full_join(fuel_access) 
```

# EDA
```{r}
indoor_pollution %>% 
  count(entity)

indoor_pollution %>% 
  distinct(year) %>% 
  arrange(-year)
```


```{r}
joined_data %>% 
  keep(is.numeric) %>% 
  gather() %>% 
  ggplot(aes(value)) + geom_histogram() + facet_wrap(~key, scales = "free")

joined_data %>%
  filter(year < 0) %>% 
  arrange(year)

fuel_access %>% 
  filter(year < 0)

indoor_pollution %>% 
  filter(year < 0)

joined_data <- 
  joined_data %>% 
  filter(year > 1900)

```

## Deaths over time
```{r}
indoor_pollution %>% 
  group_by(entity) %>% 
  summarize(diff = deaths_pct[year == 1990] - deaths_pct[year == 2019]) %>% 
  arrange(-diff)

tidy_pollution <- indoor_pollution %>% 
  nest(-entity) %>% 
  mutate(model = map(data, ~lm(deaths_pct ~ year, .x)),
         tidy = map(model, broom::tidy)) %>% 
  unnest(tidy)

tidy_pollution %>% 
  filter(term == "year") %>% 
  arrange(-abs(estimate))
```


```{r}
x <- tidy_pollution %>%
  filter(term == "year") %>% 
  arrange(-abs(estimate)) %>% 
  pull(entity)

y <- indoor_pollution %>% 
  group_by(entity) %>% 
  summarize(diff = deaths_pct[year == min(year)] - deaths_pct[year == max(year)]) %>% 
  arrange(-abs(diff)) %>% 
  pull(entity)

mean(x[1:10] == y[1:10])
mean(x == y)

```


```{r}
indoor_pollution %>% 
  filter(entity %in% x[1:10]) %>% 
  ggplot(aes(year, deaths_pct)) + geom_line() + geom_smooth(method = "lm", se = FALSE) +
  facet_wrap(~entity) + 
  labs(title = "Top 10 Countries by absolute value of slope Coefficient", y = "Percentage of deaths", x = "") + 
  scale_x_continuous(breaks = c(1995,2005,2015)) + 
  scale_y_continuous(labels = scales::percent_format(scale = 1))
```


```{r}
tidy_pollution %>% 
  filter(term == "year" & p.value > 0.05)

indoor_pollution %>% 
  filter(entity %in% (tidy_pollution %>% filter(term == "year" & p.value > 0.05) %>% pull(entity))) %>% 
  ggplot(aes(year, deaths_pct)) + geom_line() + geom_smooth(method = "lm", se = FALSE) +
  facet_wrap(~entity) +
  labs(title = "Countries with P.Values greather than 5% for slope coefficient", y = "Percentage of deaths", x = "") + 
  scale_x_continuous(breaks = c(1995,2005,2015)) + 
  scale_y_continuous(labels = scales::percent_format(scale = 1))
```


## Access
```{r}
fuel_access %>% 
  filter(!is.na(access_pct) & !is.na(continent)) %>% 
  ggplot(aes(access_pct, color = fct_reorder(continent, access_pct, median, .desc = TRUE))) + 
  geom_density() + labs(color = "Continent (Ordered by median)") +
  labs(x = "Access to clean fuel", title = "Proportion Access to Clean Fuel for each Continent") + 
  scale_x_continuous(labels = scales::percent_format(scale = 1))

fuel_access %>% 
  mutate(alpha = ifelse(is.na(continent), 0.1, 1)) %>% 
  filter(!is.na(access_pct) & !is.na(gdp)) %>% 
  ggplot(aes(gdp, access_pct, color = continent)) + geom_point(aes(alpha = alpha)) + 
  scale_x_log10(labels = scales::comma) + scale_y_continuous(labels = scales::percent_format(scale = 1)) +
  guides(alpha = "none") + 
  labs(color = "Continent", y = "Access to Clean Fuel", x = "GDP", title = "Access to fuel by GDP")
```



```{r}
joined_data %>% 
  filter(!is.na(deaths_pct) & !is.na(access_pct)) %>% 
  gather("key", "value", c("deaths_pct", "access_pct")) %>% 
  group_by(year, key) %>% 
  summarize(avg = mean(value)) %>% 
  ggplot(aes(year, avg, color = key)) + geom_line() + geom_point() +
  labs(y = "Average", color = "", title = "Average Fuel and Deaths by Year") + 
  scale_y_continuous(labels = scales::percent_format(scale = 1)) +
  scale_color_discrete(labels = c("Access to Fuel", "Deaths")) + 
  theme(legend.position = "top", plot.title = element_text(hjust = 0.5))
```

