---
title: "Pride Donations"
author: "Matthew"
date: '2022-06-07'
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, dpi = 500)
library(tidyverse)
library(patchwork)
theme_set(theme_bw())
```


```{r}
pride_aggregates <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-06-07/pride_aggregates.csv')
fortune_aggregates <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-06-07/fortune_aggregates.csv')
static_list <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-06-07/static_list.csv')
pride_sponsors <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-06-07/pride_sponsors.csv')
corp_by_politicians <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-06-07/corp_by_politician.csv')
donors <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-06-07/donors.csv')
```




```{r}
fortune_aggregates <- fortune_aggregates %>% 
  rename_with(tolower) %>% 
  rename_with(~ sub('# of ', '', .x))

fortune_aggregates %>% 
  arrange(-`total contributed`) %>%
  filter(company != "Grand Total") %>% 
  head(20) %>% 
  ggplot(aes(`total contributed`, 
             fct_reorder(company, `total contributed`),
             label = `politicians contributed to`)) + 
  geom_col(color = "black", fill = "lightblue") + 
  labs(y = "Company", fill = "Politicians",
       title = "Contributions made to anti-LGBTQ Politicians") +
  scale_x_continuous(labels = dollar) + geom_text(nudge_x = -30000)
```


```{r}
static_list %>% 
  filter(`Pride?` == TRUE) %>% 
  arrange(-`Amount Contributed Across States`) %>% 
  head(20) %>% 
  ggplot(aes(`Amount Contributed Across States`, 
             fct_reorder(Company, 
                         `Amount Contributed Across States`),
             label = `# of Politicians Contributed to`)) +
  geom_col(color = "black", fill = "lightblue") + 
  geom_text(nudge_x = -2) + 
  labs(y = "", x = "Dollars (log-scale)",
       title = "Contributions made to pro-LGBTQ Politicians") +
  scale_x_log10(labels = dollar)
```



```{r}
fortune_aggregates %>% 
  filter(grepl("Enterprise", company)) %>% 
  pull(`total contributed`)

corp_by_politicians %>% 
  arrange(-`SUM of Amount`) %>%
  filter(Politician != "Grand Total") %>%
  head(20) %>% 
  ggplot(aes(`SUM of Amount`, 
             fct_reorder(Politician, `SUM of Amount`), 
             fill = fct_reorder(Title, 
                                `SUM of Amount`, 
                                max, 
                                .desc = TRUE))) + 
  geom_col(color = "black") +
  scale_x_log10(labels = dollar) + 
  labs(y = "Politician",
       x = "Dollars (log scale)", fill = "Title",
       title = "Contributions received by anti-LGBTQ politicians")
```


# Checking 'Grand Total'
```{r}
fortune_aggregates %>% 
  mutate(grand = ifelse(company == "Grand Total", "Yes", "No")) %>% 
  group_by(grand) %>% 
  summarize(sum(`total contributed`))
```





