---
title: "Egg Production"
author: "Matthew"
date: "04/13/23"
output: 
  github_document:
    toc: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, dpi = 500, fig.showtext = TRUE)
library(tidyverse)
library(lubridate)
library(scales)
library(patchwork)
library(sysfonts)
library(showtext)
font_add_google("Roboto Slab", "Roboto")
theme_set(theme_minimal())
theme_update(plot.title = element_text(hjust = 0.5),
             plot.subtitle = element_text(hjust = 0.5),
             text = element_text(family = "Roboto"))
showtext_auto()
```

```{r, message = FALSE}
eggproduction  <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-04-11/egg-production.csv')
cagefreepercentages <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-04-11/cage-free-percentages.csv')
```

# EDA

## Hens

```{r}
eggproduction %>% 
  ggplot(aes(observed_month, n_hens, color = prod_process)) +
  geom_point() +
  scale_y_log10()

eggproduction %>% 
  filter(prod_process == "all") %>% 
  ggplot(aes(observed_month, n_hens, color = prod_type)) +
  geom_point()
```
