---
title: "Product Hunt"
author: "Matthew"
date: "2022-10-04"
output: 
  github_document:
    toc: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, dpi = 500)
library(tidyverse)
library(tidytext)
library(scales)
theme_set(theme_bw())
```

# EDA

```{r}
product <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-10-04/product_hunt.csv')
```

```{r}
knitr::kable(head(product[,1:6]))
knitr::kable(head(product[,7:12]))

skimr::skim(product)
```

```{r}
product %>% 
  count(makers, sort = TRUE)
```

```{r}
product %>% 
  ggplot(aes(upvotes)) + geom_histogram() +
  scale_x_log10()
```

## Most Common Words in Product Description

```{r}
product %>% 
  unnest_tokens(word,product_description) %>% 
  anti_join(stop_words) %>%
  mutate(word = fct_lump(word, 10)) %>% 
  filter(word != "Other", !is.na(word)) %>% 
  group_by(word) %>% 
  summarize(m = mean(upvotes, na.rm = TRUE)) %>% 
  arrange(-m) %>% 
  ggplot(aes(m, fct_reorder(word, m))) + geom_col(color = "black", fill = "lightblue") +
  labs(y = "Words", x = "Average Upvotes", title = "Average Upvotes of Products Based on the 10 Most Common Words")
```

## Releases of Time

```{r}
product %>% 
  count(release_date, sort = TRUE) %>% 
  ggplot(aes(release_date, n)) + geom_point(alpha = 0.2) +
  geom_smooth() + labs(title = "Number of Releases over Time", x = "Date", y = "Releases")
```

## Most Upvoted Products

```{r}
product %>% 
  slice_max(upvotes, n = 10) %>% 
  ggplot(aes(upvotes, fct_reorder(name, upvotes))) + 
  geom_col(color = "black", fill = "lightgreen") +
  labs(y = "Product Name")
```

```{r}
product_tags <- product %>% 
  mutate(category_tags = str_split(category_tags, "', ")) %>% 
  unnest(category_tags) %>% 
  mutate(category_tags = str_remove_all(category_tags, "\\[|'|\\]"))

product_tags %>% 
  group_by(category_tags) %>% 
  summarize(Median = median(upvotes, na.rm = TRUE)) %>% 
  slice_max(Median, n = 10) %>% 
  ggplot(aes(Median, fct_reorder(category_tags, Median))) + 
  geom_col(color = "black", fill = "lightpink") +
  labs(title = "Top 10 Median Upvotes of Products by Category Tags") + 
  ggthemes::theme_fivethirtyeight() +
  theme(plot.title = element_text(hjust = 0.5))
```

